version: '3.7'

networks:
  net:
    driver: bridge
    external: true
    name: net

volumes:
  postgres_data:

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - net
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/digital
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8082:80
    networks:
      - net
