version: '3.7'

networks:
  net:
    driver: bridge
    external: true
    name: net

volumes:
  mongo_data:

services:
  mongo:
    image: mongo:6.0.5
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassXXX
    ports:
      - 27017:27017

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express:latest
    restart: always
    ports:
      - 8083:8081
    networks:
      - net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: D123456
      ME_CONFIG_MONGODB_URL: mongodb://root:D123456@mongo:27017/
